
name: CI
on:
  pull_request:
    branches: [ master ]
    types: ['labeled', 'synchronize','assigned','labeled','reopened','review_requested']

jobs:
  check_pr_milestone:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Create commits
      run: |
          git config user.name 'Peter Evans'
          git config user.email 'peter-evans@users.noreply.github.com'
          date +%s > report.txt
          git commit -am "Modify tracked file during workflow"
          date +%s > new-report.txt
          git add -A
          git commit -m "Add untracked file during workflow"
    - name: Uncommitted change
      run: date +%s > report.txt
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v2 
