# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  pull_request:
    branches: [ master ]
    types: [assigned,labeled,reopened,edited,review_requested]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/verify-pr-label-action@v1.0.0
      with:
         github-token: '${{ secrets.GITHUB_TOKEN }}'
         valid-labels: 'patch, major, minor, none'    
