
name: CI
on:
  pull_request:
    branches: [ master ]
    types: ['closed']
jobs:

  check_pr_milestone:
    runs-on: ubuntu-latest
    if: ! contains(github.event.pull_request.labels.*.name, 'heat')
    steps:
    - uses: actions/checkout@v2
