
name: CI
on:
  pull_request:
    branches: [ master ]
    types: ['labeled', 'synchronize','assigned','labeled','reopened','review_requested']

jobs:
  check_pr_milestone:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/verify-pr-label-action@v1.0.0
      with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
          valid-labels: 'bug, patch'
